site_name: lernOS für Dich Leitfaden

docs_dir: src

site_dir: ../docs/en

nav:
    - About lernOS: index.md
    - Introduction:
        - Introduction: 1-0-Introduction.md
        - lernOS Sprints: 1-1-lernOS-Sprints.md
        - lernOS Wheel: 1-2-lernOS-Wheel.md
        - lernOS Circle: 1-3-lernOS-Circle.md
    - Learning Paths:
        - Learning Paths: 2-0-Learning-Paths.md
        - WOL Learning Path:
            - WOL Learning Path: 2-1-0-Learning-Path-WOL.md
            - Design Your Future Backwards (Kata): 2-1-1-Kata-1.md
            - Think visual with the lernOS Canvas (Kata): 2-1-2-Kata-2.md
            - My Objective For The Next 12 weeks (Kata): 2-1-3-Kata-3.md
            - People Related To Your Objective (Kata): 2-1-4-Kata-4.md
            - Your First Sharing Experience (Kata): 2-1-5-Kata-5.md
            - An Appointment With Yourself (Kata): 2-1-6-Kata-6.md
            - Go Google Yourself (Kata): 2-1-7-Kata-7.md
            - 25 Facts About Me (Kata): 2-1-8-Kata-8.md
            - Your Top 10 Assets (Kata): 2-1-9-Kata-9.md
            - Update Your Digital Twin (Kata): 2-1-10-Kata-10.md
            - Find Communities Related To Your Objectives (Kata): 2-1-11-Kata-11.md
            - Contribute Your Self (Kata): 2-1-12-Kata-12.md
            - Write A Letter To Your Future Self (Kata): 2-1-13-Kata-13.md
        - OKR Learning Path:
            - OKR Learning Path: 2-2-0-Learning-Path-OKR.md
            - Top 10 Sources of OKRs (Kata): 2-2-1-Kata-1.md
            - Set up your OKR environment (Kata): 2-2-2-Kata-2.md
            - Define OKRs for your Sprint (Kata): 2-2-3-Kata-3.md
            - Finalize your OKRs for the Sprint (Kata): 2-2-4-Kata-4.md
            - Perform your Weekly Check-In (Kata): 2-2-5-Kata-5.md
            - Tools for OKRs (Kata): 2-2-6-Kata-6.md
            - Scoring vs. Measuring Key Results (Kata): 2-2-7-Kata-7.md
            - Stretch Goals and Moonshots (Kata): 2-2-8-Kata-8.md
            - What is your Confidence Level? (Kata): 2-2-9-Kata-9.md
            - Individual vs. Team/Organizational OKRs (Kata): 2-2-10-Kata-10.md
            - OKR Review (Kata): 2-2-11-Kata-11.md
        - GTD Learning Path:
            - GTD Learning Path: 2-3-0-Learning-Path-GTD.md
            - Get to know the basics (Kata): 2-3-1-Kata-1.md
            - Collect - Mind Sweep (Kata): 2-3-2-Kata-2.md
            - Processing - The 2 minute rule (Kata): 2-3-3-Kata-3.md
            - Organize - Build Lists & Contexts (Kata): 2-3-4-Kata-4.md
            - Review - The Weekly Review (Kata): 2-3-5-Kata-5.md
            - Doing (Kata): 2-3-6-Kata-6.md
            - Projects - Become like the kids (Kata): 2-3-7-Kata-7.md
            - Work through the 5 phases (Kata): 2-3-8-Kata-8.md
            - The Power of the Next Step (Kata): 2-3-9-Kata-9.md
            - The 6-horizon model (Kata): 2-3-10-Kata-10.md
            - Continuous Improvement - The Road to Mastery (Kata): 2-3-11-Kata-11.md
    - Appendix: 3-Appendix.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-for-you'
repo_url: 'https://github.com/cogneon/lernos-for-you'

extra:
    social:
        - type: 'twitter'
          link: 'https://twitter.com/lern_os'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/showcase/lern-os'
        - type: 'github'
          link: 'https://github.com/cogneon'
    disqus: lernos