site_name: lernOS für Dich Leitfaden

docs_dir: src

site_dir: ../docs/en

nav:
    - About lernOS: 1-About-lernOS.md
    - Introduction: 2-Introduction.md
    - Learning Paths:
        - Learning Paths: 3-0-Learning-Paths.md
        - WOL Learning Path: 3-1-Learning-Path-WOL.md
        - OKR Learning Path: 3-2-Learning-Path-OKR.md
        - GTD Learning Path: 3-3-Learning-Path-GTD.md
    - Appendix: 4-Appendix.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-for-you'
repo_url: 'https://github.com/cogneon/lernos-for-you'

extra:
    social:
        - type: 'twitter'
          link: 'https://twitter.com/lern_os'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/showcase/lern-os'
        - type: 'github'
          link: 'https://github.com/cogneon'
