site_name: lernOS für Dich Leitfaden

docs_dir: src

site_dir: ../docs/de

nav:
    - Über lernOS: index.md
    - Grundlagen: 1-Grundlagen.md
    - Lernpfade:
        - Lernpfade: 2-0-Lernpfade.md
        - WOL Lernpfad:
            - WOL Lernpfad: 2-1-0-Lernpfad-WOL.md
            - Lege dein Ziel für die nächsten 12 Wochen fest (Kata 1): 2-1-1-Kata-1.md
            - Wer kann dir bei deinem Ziel helfen? (Kata 2): 2-1-2-Kata-2.md
            - Teile etwas im Netzwerk (Kata 3): 2-1-3-Kata-3.md
            - Mache Termine mit dir selbst (Kata 4): 2-1-4-Kata-4.md
            - Egosurfe dich! (Kata 5): 2-1-5-Kata-5.md
            - Beschreibe dich mit 25 Tags (Kata 6): 2-1-6-Kata-6.md
            - Aktualisiere deinen digitalen Zwilling (Kata 7): 2-1-7-Kata-7.md
            - Poste deine Top 10 Trüffel (Kata 8): 2-1-8-Kata-8.md
            - Welche Kanäle willst du nutzen? (Kata 9): 2-1-9-Kata-9.md
            - Welche Communities können dir helfen? (Kata 10): 2-1-10-Kata-10.md
            - Schreibe einen Brief an dein zukünftiges Ich (Kata 11): 2-1-11-Kata-11.md
        - OKR Lernpfad: 2-2-Lernpfad-OKR.md
        - GTD Lernpfad: 2-3-Lernpfad-GTD.md
    - Anhang: 3-Anhang.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-for-you'
repo_url: 'https://github.com/cogneon/lernos-for-you'

extra:
    social:
        - type: 'twitter'
          link: 'https://twitter.com/lern_os'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/showcase/lern-os'
        - type: 'github'
          link: 'https://github.com/cogneon'
    disqus: lernos