theme: jekyll-theme-cayman
title: lernOS
description: The Method for Living, Learning & Working in the 21st Century. It's free and it's open!
show_downloads: false
github:
  en_url: https://github.com/simondueckert/lernos/blob/master/lernOS%20Guide/en/lernOS-Guide-en.md
  de_url: https://github.com/simondueckert/lernos/blob/master/lernOS%20Guide/de/lernOS-Guide-de.md
