theme: jekyll-theme-cayman
title: lernOS
description: The Method for Living, Learning & Working in the 21st Century
show_downloads: true
github:
  en_url: https://github.com/simondueckert/lernos/raw/master/lernOS%20Guide/en/lernOS-Guide-en.pdf
  de_url: https://github.com/simondueckert/lernos/raw/master/lernOS%20Guide/en/lernOS-Guide-en.pdf
